server:
  port: 8080
spring:
  application:
    name: "customers"
  datasource:
    url: "jdbc:h2:file:~/customers;AUTO_SERVER=true"
    driver-class-name: "org.h2.Driver"
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
  cloud:
    function:
      definition: updateMobileNumberStatus;rollbackCustomerMobileNumber
    stream:
      bindings:
        updateAccountMobileNumber-out-0:      # This sends the message to update mobile number in accounts database
          destination: update-account-mobile-number
#        updateCardMobileNumber-out-0:
#          destination: update-card-mobile-number
        updateMobileNumberStatus-in-0:
          destination: update-mobile-number-status
          group: ${spring.application.name}
        rollbackCustomerMobileNumber-in-0:    # This receives the message to rollback mobile number in customers database
          destination: rollback-customer-mobile-number
          group: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "customers"
    description: "Easy Bank Customers Application"
    version: "1.0.0"

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"